services:
  # 1. Ваш Node.js / Express застосунок
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000' # Відкриваємо порт тільки для веб-застосунку
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Чекаємо повної готовності Postgres
    # Накатуємо схему бази через Prisma та запускаємо застосунок
    command: >
      sh -c "npx prisma db push && node ./src/index.js"

  # 2. Сервіс Бази Даних (PostgreSQL)
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d user_app']
      interval: 3s
      timeout: 3s
      retries: 5

volumes:
  pgdata: # Зберігає дані бази між перезапусками контейнерів
