version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://postgres:secret@db:5432/mydb
    depends_on:
      - db
    # Обмеження використання оперативної пам'яті на VPS
    deploy:
      resources:
        limits:
          memory: 512M

  # Приклад бази даних (PostgreSQL)
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_app
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 256M

volumes:
  pgdata:
